import { CatalogExpirationComponent } from './../component/planner-queue/alerts/catalog-expiration/catalog-expiration.component';

export class PartNumber {
    public SYSTEM: string;
    public SOURCE: string;
    public COMMODITY: string;
    public ME_PART_NUMBER: string;
    public MFG_PART_NUMBER: string;
    public MFCTR_ID: string;
    public KEYWORD: string;
    public PART_TYPE: string;
    public CPN: string;
    public ATA: string;
    public PLANNER: string;
    public FLEET_CODE: string;
    public ESS_CODE: string;
    public UOM: string;
    public CATALOG_PRICE: number;
    public MATERIAL_TYPE: string;
    public OWNERSHIP: number;    
    public HAZARDOUS_MATERIAL: string;
    public SUPERVISOR: string;
    public Sched_Mntnc: string;
    public ECO: string;
    public IN_KIT: string;
    public BUYER_NAME: string;
    public RO_ADMIN: string;
    public SHELF_LIFE: number;
    public CATALOG_AMOUNT: number;
    public AUP: number;
    public LAST_PO_PRICE: number;
    public IPC_FLEET: string;
    public Fill_to_Allocation: number;
    public ZS_Rate: number;
    public Eff_Group: string;
    public BUY_IND: string;
    public STOCK_IND: string;
    public OPTIMAL_OWNERSHIP: number;
    public IPC_DESCRIPTION: string;
}
